### ISSUE TITLE
ConsulDiscoveryClientConfiguration depends on ServerProperties

### ISSUE THREAD

**Issue by GuiForget** [spring-cloud/spring-cloud-consul#149]
I'm currently using ConsulDiscoveryClient with Brixton.M3 and I'm trying to upgrade to Brixton.M5 and I'm hitting a road block which has been introduced with this commit:
https://github.com/spring-cloud/spring-cloud-consul/commit/518958e408c1573984773d90d16bcc44f6a54f2e

Basically, if I'm not mistaken we're saying that the ConsulDiscoveryClient can only be used in the context of a webapp (since ServerPropertiesAutoConfiguration has @ConditionalOnWebApplication). This doesn't seem correct to me since I can have a command line application that should be able to use the consul client to discover services registered with consul.

**Comment by GuiForget** [comment]
To avoid the missing ServerProperties bean, I ended up registering one in my own Configuration.

**Comment by spencergibb** [comment]
Currently yes. The lifecycle is a holdover from eureka which had to register to use the discovery client. Shouldn't be hard to make a flag to disable registering. Likely in the Camden release we will introduce a `Registration` interface and maybe annotation since registering with discovery and using discovery are really separate concerns.
