### ISSUE TITLE
Adds ability to deregister a service based on critical check state longer than a timeout

### ISSUE THREAD

**Issue by panga** [spring-cloud/spring-cloud-consul#210]
Based on this PR (https://github.com/hashicorp/consul/pull/2276) that will be released with Consul 7.0, please provide property to define and deregister zombie services automatically.

**Comment by spencergibb** [comment]
That property will need to be added the consul library we use https://github.com/Ecwid/consul-api/issues

**Comment by dwelch2344** [comment]
Was just about to file an issue about adding support for this. Will open an issue there and submit a PR, then follow up here. 

Assuming the property is there, where would be the best place to make it configurable? I'd imagine a property from `application.yml` would be desirable, no? 

Happy to contribute on this

**Comment by spencergibb** [comment]
The issue is already there https://github.com/Ecwid/consul-api/issues/64.  I would assume the property would go in [`ConsulDiscoveryProperties`](https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-discovery/src/main/java/org/springframework/cloud/consul/discovery/ConsulDiscoveryProperties.java)

**Comment by spencergibb** [comment]
Ping @dwelch2344
