### ISSUE TITLE
Support random server.port

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud/spring-cloud-consul#23]

**Comment by beeva-pablovaliente** [comment]
Hello @spencergibb , is this bug solved??

I am testing a really simple hello-service that registers itself in consul. I am trying to use the random port (server.port=0), not in the bootstrap of the service but in Consul K/V. (`config/hello-service/server.port=0`)
The result is that the application server of the service (Undertow) is using a random port to start listening to, but to register in consul, the service is using the port '0'.

A request to `http://localhost:8500/v1/agent/services` give us a result:
```json
"hello-service": {
    "ID": "hello-service",
    "Service": "hello-service",
    "Tags": [],
    "Address": "110.23.47.85",
    "Port": 0,
    "EnableTagOverride": false,
    "CreateIndex": 0,
    "ModifyIndex": 0
  }
```
So the service is never shown as PASSING (obviously).

I am using the recent milestone **1.0.2** for Spring Cloud Consul.

Thanks

**Comment by spencergibb** [comment]
@beeva-pablovaliente I just tried it with CLI arg `--server.port=0` and it works. Unknown how it behaves from consul-kv. Open a new issue if you can reliably reproduce it.

**Comment by beeva-pablovaliente** [comment]
Thanks @spencergibb.

As you said, using CLI arg or bootstrap.yml it works correctly, the misbehavior happens when server.port is set in Consul KV. Also, if server.port is set in Consul KV, when you try to overwrite the value using CLI arg or environment variable for example, nothing happens. It looks like if KV has more precedence than CLI arg or any other property source.
