### ISSUE TITLE
Cannot disable consul health indicator in Grails application

### ISSUE THREAD

**Issue by theAmneziac** [spring-cloud/spring-cloud-consul#315]
Follow up issue related to #234.

I have `management.health.consul.enabled = false` set in my configuration, but the consul health indicator is still present in my health check.

@spencergibb I realize now that this problem only happens when I include spring-cloud-starter-consul-all in a Grails application.  It doesn't happen in a plain Spring application.  Do you have any intuition about this?

To make the issue occur, I used `grails create-app` to generate a new Grails application, set `endpoints.enabled: true` in the configuration file (to make the health endpoint available), then included `org.springframework.cloud:spring-cloud-starter-consul-all` with gradle.  That caused the health endpoint to appear and to show the Consul health indicator, as well as 3 others: "diskSpace", "hystrix", and "refresh".

By putting `management.health.***.enabled = false` in the config file, where *** is any of "diskspace", "hystrix", or "refresh", I can turn the respective indicator off.  But, for some reason, this does _not_ work for the Consul health indicator.

Here is a link to a project that recreates the problem:
[https://github.com/theAmneziac/grails-consul-health-indicator-example](url)

Thanks for your time.  I realize the twist of this only occurring in Grails applications is annoying.  If you don't have an intuition about it, or you think it's an issue with Grails and not with Spring Cloud Consul, I totally understand.

**Comment by spencergibb** [comment]
Can you try importing the spring-cloud-dependencies bom rather than the consul dependencies?

**Comment by chengchen** [comment]
We experienced the same problem as well.

The issue is that all the consul stuff are initialized in the very beginning before all your configs are loaded. So what I did is to put the management.health.consul.enabled = false in the bootstrap.yml and this would disable the creation of ConsulHealthIndicator.

**Comment by spencergibb** [comment]
> The issue is that all the consul stuff are initialized in the very beginning before all your configs are loaded.

Who does "your"  refer to?

**Comment by theAmneziac** [comment]
@chengchen That worked perfectly, thank you for posting.
@spencergibb sorry I didn't get back to you about your bom idea, I was going to try it later when I was less busy.

**Comment by chengchen** [comment]
@spencergibb Sorry about the misunderstanding, I was talking about the normal application.yml

When ConsulAutoConfiguration decides if it needs to add the ConsulHealthIndicator, he will check if management.health.consul.enabled = true, or management.health.defaults.enabled = true OR it's not configured. Since consul are initialized before almost everything, the application.yml is not yet loaded (ConsulAutoConfiguration thinks management.health.defaults.enabled is not configured), it will simply creates the ConsulHealthIndicator.

However, if you add the bootstrap.yml, then the configuration will be taken into account.
