### ISSUE TITLE
Compatibility with Consul 1.0.0

### ISSUE THREAD

**Issue by vvsh** [spring-cloud/spring-cloud-consul#365]
Hi,

I tried to update my Consul to 1.0.0 and now I see that health check is down and error is IllegalArgumentException: Value must not be null.

I see that consul-api [is not yet compatible](https://github.com/Ecwid/consul-api/issues/130) with Consul 1.0.0 but I am not sure that it is only one issue.

Thanks,
Uladzimir

**Comment by spencergibb** [comment]
We will have to wait for https://github.com/Ecwid/consul-api/issues/130

**Comment by preetapan** [comment]
@spencergibb I work on Consul at Hashicorp. Wanted to propose an alternate solution. Instead of waiting on ecwid/Consul-api to fix parsing of the v1/agent/self , you could change the [health indicator]( https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-consul-core/src/main/java/org/springframework/cloud/consul/ConsulHealthIndicator.java#L43) to stop reading agent/self altogether. IIUC, the goal of this class is to make sure Consul is up and running, and fail if it is not up. If you switched the code in `doHealthCheck` to using the [leader status endpoint](https://github.com/Ecwid/consul-api/blob/master/src/main/java/com/ecwid/consul/v1/status/StatusClient.java#L12), that tells you whether Consul agent is up and is able to talk to a leader. It is also a stable API that's not likely to change, whereas reading configuration values like advertise address and bind address are implementation details that things that depend on Consul shouldn't need to care about for health check purposes. 

I hope this makes sense, let me know if you want a PR from me or your team can do this.

**Comment by spencergibb** [comment]
Sounds good! PRs welcome

**Comment by preetapan** [comment]
PR https://github.com/spring-cloud/spring-cloud-consul/pull/370

**Comment by vgv** [comment]
> We will have to wait for Ecwid/consul-api#130

Hi, I've released it today

**Comment by spencergibb** [comment]
Thanks!

**Comment by spencergibb** [comment]
Great https://github.com/Ecwid/consul-api/milestone/10?closed=1 and it's in maven central.

**Comment by sac36837** [comment]
When will this release be available in Maven Central?
