### ISSUE TITLE
How can I set consistency mode to stale for QueryParam 

### ISSUE THREAD

**Issue by JakubKrhovjak** [spring-cloud/spring-cloud-consul#556]
Hi. I  like to know if possible set  consistency mode to stale when querying consul? I cannot see a way to change it from DEFAULT. I find out that there is class ConsulCatalogWatch responsible for creating QueryParam but I was not able to rewrite its behavior.

It would be nice have property like spring.cloud.consul.config.consistency-mode=STALE

Thanks 
Japca

**Comment by ryanjbaxter** [comment]
What version of Spring Cloud and Consul?  Can you provide some details around the problem this is causing?

**Comment by Japca** [comment]
Hi, I'm using version 2.1.1 RELEASE. 
In my case problem occures when a cluster has set bootstrap_expect=2 an  I have only one instance up. In this case, I cannot start any of my SpringBoot client's apps. 

This log to output:

Fail fast is set and there was an error reading configuration from consul.

I was able to change Consistency mode to STALE via reflection, at least to start apps  but it would be nice to have an option to do that simply and cleaner way.

**Comment by OlgaMaciaszek** [comment]
Hello @Japca , thanks for the suggestion. We will discuss the possibility of adding a property. In the meantime, as a workaround, you could use a `ConsulDiscoveryClient` bean instead of the `DiscoveryClient` abstraction.
This way, you could pass your own `QueryParams` object while querying for instances, like so:
`discoveryClient.getInstances("bar", new QueryParams(ConsistencyMode.STALE));`
It's not perfect, but still probably better than reflection. Let me know if this works for you.

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
