### ISSUE TITLE
spring-cloud-starter-consul-discovery depends on spring-cloud-starter-netflix-ribbon

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-consul#562]
_spring-cloud-starter-consul-discovery_ depends on _spring-cloud-starter-netflix-ribbon_ although _Spring Cloud Netflix Ribbon_ is in maintenance mode.
Please see https://github.com/spring-cloud/spring-cloud-consul/blob/master/spring-cloud-starter-consul-discovery/pom.xml#L38

Maybe an optional dependency is needed as @spencergibb commented in https://github.com/spring-cloud/spring-cloud-netflix/issues/3415#issuecomment-499987855

**Comment by juergenzimmermann** [comment]
@spencergibb _spring-cloud-consul 2.2.0.M2_ still depends on _spring-cloud-starter-consul-discovery_ depends on _spring-cloud-starter-netflix-ribbon_: https://github.com/spring-cloud/spring-cloud-consul/blob/v2.2.0.M2/spring-cloud-starter-consul-discovery/pom.xml#L34

**Comment by OlgaMaciaszek** [comment]
In order to preserve backward compatibility, we will not be removing the `spring-cloud-starter-netflix-ribbon` dependency until we do a major release. However, as part of the Hoxton release train, we are adding `spring-cloud-starter-loadbalancer` dependency, which will allow the users to switch to using the non-maintenance `BlockingLoadBalancerClient` instead of the `RibbonLoadBalnacerClient` underneath.

Consequently, we will be completely removing all maintenance-mode dependencies with the next major release.

**Comment by OlgaMaciaszek** [comment]
Fixed in `3.0.0.M1`.
