### ISSUE TITLE
ConsulReactiveDiscoveryClient.getInstances("...") returns an empty Flux

### ISSUE THREAD

**Issue by juergenzimmermann** [spring-cloud/spring-cloud-consul#593]
Using _Spring Cloud Hoxton.M3_ (spring-cloud-starter-config, spring-cloud-starter-consul-discovery which includes spring-cloud-starter-loadbalancer) and _Consul 1.6.1_ the following Kotlin fragment yields a Flux with 3 items:

- _consul_: i.e. Consul itself
- _config_: a registered config server with _Spring Cloud Config_
- _kunde_: a homegrown microservice _kunde_.

```
@Bean
fun discoveryClient(discoveryClient: ReactiveDiscoveryClient) = CommandLineRunner {
    val logger = ...
    discoveryClient.services
        .subscribe { service -> logger.warn("Registered Service: $service") }
}
```

However, the following Kotlin fragment results in an empty Flux when querying for the *existing* service _kunde_:

```
@Bean
fun discoveryClientKunde(discoveryClient: ReactiveDiscoveryClient) = CommandLineRunner {
    val logger = ...
    discoveryClient.getInstances("kunde")
        .collectList() // converts (empty) Flux to Mono with (empty) List
        .subscribe { instances -> logger.warn("Instances: $instances") }
}
```

The plain Consul implementation (as in `ConsulReactiveDiscoveryClient.getInstances()`) works fine:
```
@Bean
fun consulClientKunde(consulClient: ConsulClient) = CommandLineRunner {
    val logger = ...
    val response = consulClient.getHealthServices("kunde", null, false, QueryParams.DEFAULT)
    val healthService = response.value[0]
    val metadata = ConsulServerUtils.getMetadata(healthService)
    val https = if (java.lang.Boolean.parseBoolean(metadata["secure"])) "https" else "http"
    val host = ConsulServerUtils.findHost(healthService)
    val port = healthService.service.port
    logger.warn("Instances: $https://$host:$port")
}
```

Providing a testcase might be cumbersome (Consul, Config, microservice, ...). Please guide me to give you additional information.

**Comment by spencergibb** [comment]
@TYsewyn if you don't have cycles let me know and we can investigate.

**Comment by TYsewyn** [comment]
So the issue appears to reside in `ReactiveCompositeDiscoveryClient`, specifically in `return Flux.first(serviceInstances);`.
`Flux.first` will return the first flux in the list of `serviceInstances` that emits any signal (onNext/onError/onComplete). Since the `SimpleReactiveDiscoveryClient` is being bootstrapped by default too and there is currently no way of en-/disabling this via properties, you will always end up having no instances (except if you have instances added to your properties file).
The fastest workaround is to use `ConsulReactiveDiscoveryClient` instead of `ReactiveDiscoveryClient`.

**Comment by TYsewyn** [comment]
See spring-cloud/spring-cloud-commons#617
